language: python
sudo: enabled
dist: trusty
group: edge

# whitelist master branch only
branches:
  only:
    - master

python:
  - "3.5"

install: ./.travis_ci/prepare.sh

script: ./run_tests.sh

after_failure: "cat /tmp/zutils.log"
